#make sure that you configure HOME_DIR env variable in .env file.
version: '3'
services:
  label-studio:
    container_name: "label-studio"
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    #    environment:
    #      - EXPERIMENTAL_FEATURES=true
    volumes:
      - ${HOME_DIR}/label-studio-images:/label-studio/data:rw
    ports:
      - 18888:8080
  ml:
    container_name: "ml"
    build:
      context: ./ml_docker
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      - mqtt_broker_host=${mqtt_broker_host}
      - mqtt_broker_port=${mqtt_broker_port}
      - mqtt_broker_login=${mqtt_broker_login}
      - mqtt_broker_password=${mqtt_broker_password}

