yolo_weights: /usr/src/datasets/yolo_detection_model.pt
keras_weights: /usr/src/datasets/keras_home_automation_training.h5
mqtt_broker_login: mqtt_user
mqtt_broker_password: mqtt_pwd
mqtt_broker_port: 1883
mqtt_broker_host: localhost
cameras:
  mac_m1_laptop_cam:
    url: 0
    switches:
      - Switch
